$LOAD_PATH.unshift File.dirname(__FILE__) + '/../../lib'
$LOAD_PATH.unshift File.dirname(__FILE__) unless $LOAD_PATH.include?(File.dirname(__FILE__))
require 'resque/tasks'
require 'job'

desc "Start the demo using `rackup`"
task :start do
  `redis-server /etc/redis.conf`
  `QUEUE=default rake resque:work &`
  `rackup config.ru -o 0.0.0.0 -p 9292`
end
